/*
 * libkeepass - KeePass key database importer/exporter
 * Copyright (C) 2014 Christian Kindahl
 * Copyright (C) 2024 Dominik Krümpelmann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file random.hh
 * @brief Random data generation and obfuscation for KDBX inner streams.
 */

#pragma once
#include "cipher.hh"
#include "libkeepass/export.hh"

#include <memory>
#include <random>
#include <vector>

namespace keepass {

/**
 * Obfuscates binary data by xorring each byte with psuedo random data
 * generated by a Salsa20 or ChaCha20 stream cipher.
 */
class LIBKEEPASS_API RandomObfuscator {
public:
  /** Inner random stream ciphers supported by KDBX 4. */
  enum class Type {
    kSalsa20, ///< Salsa20 stream cipher (KDBX 3 and 4).
    kChaCha20 ///< ChaCha20 stream cipher (KDBX 4).
  };

private:
  Type type_ = Type::kSalsa20;
  Salsa20Cipher salsa_cipher_;
  ChaCha20Cipher chacha_cipher_;

  std::array<uint8_t, 64> buffer_{};
  std::size_t buffer_pos_ = 64;

  void FillBuffer();

public:
  /**
   * @brief Constructs a random stream cipher from a raw key and initialization vector.
   * @param key The 32-byte key for the stream cipher.
   * @param init_vec The 8-byte initialization vector.
   */
  RandomObfuscator(const std::array<uint8_t, 32>& key, const std::array<uint8_t, 8>& init_vec);

  /**
   * Constructs a random stream cipher from the raw inner random stream key
   * using the key transformation rule of the KDBX 4 format. For Salsa20 the
   * key is hashed with SHA-256 and used with a fixed IV. For ChaCha20 the key
   * is hashed with SHA-512 and split into a 32 byte key and 12 byte IV.
   */
  RandomObfuscator(Type type, const std::array<uint8_t, 32>& stream_key);

  /**
   * Constructs a random stream cipher from the raw inner random stream key of
   * KDBX 4, which may be 32 or 64 bytes depending on the writer.
   */
  RandomObfuscator(Type type, const std::vector<uint8_t>& stream_key);

  /// Obfuscates or deobfuscates a byte vector using the random stream.
  /**
   * @param data The data to process (xor with the random stream).
   * @return The processed data.
   */
  std::vector<uint8_t> Process(const std::vector<uint8_t>& data);

  /// Obfuscates or deobfuscates a string using the random stream.
  /**
   * @param data The string data to process.
   * @return The processed string.
   */
  std::string Process(const std::string& data);
};

/// Generates an array of N cryptographically random bytes.
/**
 * @tparam N The number of random bytes to generate.
 * @return An array filled with uniformly distributed random bytes in [0, 255].
 */
template <std::size_t N> std::array<uint8_t, N> random_array() {
  std::random_device rd;
  std::mt19937 engine(rd());

  std::uniform_int_distribution<int> uniform_dist(0, 255);

  // Fill block with random values.
  std::array<uint8_t, N> array;
  for (std::size_t i = 0; i < N; ++i)
    array[i] = static_cast<uint8_t>(uniform_dist(engine));

  return array;
}

} // namespace keepass
