/*
 * libkeepass - KeePass key database importer/exporter
 * Copyright (C) 2014 Christian Kindahl
 * Copyright (C) 2024 Dominik Krümpelmann
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AES-KDF hot loop using AES-NI hardware intrinsics.
 *
 * This file is compiled with -maes so the intrinsics are available only here,
 * keeping the rest of the codebase portable. The functions exported here are
 * called from Key::Transform in key.cc.
 *
 * The AES-256 key schedule is implemented with the AES-NI keygenassist
 * instruction (round keys in natural byte order, independent of any OpenSSL
 * round-key layout), and the repeated-encryption loop uses aesenc/aesenclast.
 * This mirrors how KeePassXC/Keepass implement the AES-KDF: the 32-byte
 * composite key is split into two 16-byte halves, each encrypted for `rounds`
 * iterations with AES-256-ECB using the transform seed, with the two halves
 * processed interleaved so a superscalar pipeline executes both in parallel.
 */

#include "libkeepass/aes_ni.hh"

#if LIBKEEPASS_AES_NI

#include <array>
#include <cstdint>
#include <cstring>
#include <cpuid.h>

#include <wmmintrin.h>
#include <emmintrin.h>

namespace keepass {

namespace {

// Number of round keys for AES-256 (14 rounds + 1 initial, plus one extra
// generated by the key schedule that is not used for encryption).
constexpr int kNumRoundKeys = 16;

struct Aes256RoundKeys {
  __m128i rk[kNumRoundKeys];
};

// Produces the next two AES-256 round keys using AESKEYGENASSIST. This is the
// well-known lattice/Intel algorithm; the resulting round keys are in natural
// byte order as expected by aesenc/aesenclast.
inline void NextRoundKeys(__m128i state0, __m128i state1, __m128i xword,
                          __m128i *rk0, __m128i *rk1) {
  xword = _mm_shuffle_epi32(xword, 0xff);
  xword = _mm_xor_si128(xword, state0);
  state0 = _mm_slli_si128(state0, 4);
  xword = _mm_xor_si128(xword, state0);
  state0 = _mm_slli_si128(state0, 4);
  xword = _mm_xor_si128(xword, state0);
  state0 = _mm_slli_si128(state0, 4);
  state0 = _mm_xor_si128(state0, xword);
  *rk0 = state0;

  xword = _mm_aeskeygenassist_si128(state0, 0x00);
  xword = _mm_shuffle_epi32(xword, 0xaa);
  xword = _mm_xor_si128(xword, state1);
  state1 = _mm_slli_si128(state1, 4);
  xword = _mm_xor_si128(xword, state1);
  state1 = _mm_slli_si128(state1, 4);
  xword = _mm_xor_si128(xword, state1);
  state1 = _mm_slli_si128(state1, 4);
  state1 = _mm_xor_si128(state1, xword);
  *rk1 = state1;
}

// Expand a 256-bit key into the 15 round keys needed for AES-256 encryption.
// The round constants are compile-time constants because
// _mm_aeskeygenassist_si128 requires its immediate to be constant.
Aes256RoundKeys ExpandKey(const uint8_t key[32]) {
  Aes256RoundKeys out{};

  out.rk[0] = _mm_loadu_si128(reinterpret_cast<const __m128i *>(key));
  out.rk[1] = _mm_loadu_si128(reinterpret_cast<const __m128i *>(key + 16));

  __m128i a = out.rk[0];
  __m128i b = out.rk[1];

#define LIBKEEPASS_AES256_NEXT_RK(ID, RC)                                      \
  do {                                                                         \
    __m128i xw = _mm_aeskeygenassist_si128(b, (RC));                           \
    NextRoundKeys(a, b, xw, &a, &b);                                           \
    out.rk[ID] = a;                                                            \
    out.rk[ID + 1] = b;                                                        \
  } while (0)

  // Round constants 01, 02, 04, 08, 10, 20, 40.
  LIBKEEPASS_AES256_NEXT_RK(2, 0x01);
  LIBKEEPASS_AES256_NEXT_RK(4, 0x02);
  LIBKEEPASS_AES256_NEXT_RK(6, 0x04);
  LIBKEEPASS_AES256_NEXT_RK(8, 0x08);
  LIBKEEPASS_AES256_NEXT_RK(10, 0x10);
  LIBKEEPASS_AES256_NEXT_RK(12, 0x20);
  LIBKEEPASS_AES256_NEXT_RK(14, 0x40);

#undef LIBKEEPASS_AES256_NEXT_RK

  return out;
}

// Encrypt a single 128-bit block with AES-256-ECB using AES-NI intrinsics.
inline __m128i EncryptBlock(__m128i block, const Aes256RoundKeys &keys) {
  block = _mm_xor_si128(block, keys.rk[0]);
  block = _mm_aesenc_si128(block, keys.rk[1]);
  block = _mm_aesenc_si128(block, keys.rk[2]);
  block = _mm_aesenc_si128(block, keys.rk[3]);
  block = _mm_aesenc_si128(block, keys.rk[4]);
  block = _mm_aesenc_si128(block, keys.rk[5]);
  block = _mm_aesenc_si128(block, keys.rk[6]);
  block = _mm_aesenc_si128(block, keys.rk[7]);
  block = _mm_aesenc_si128(block, keys.rk[8]);
  block = _mm_aesenc_si128(block, keys.rk[9]);
  block = _mm_aesenc_si128(block, keys.rk[10]);
  block = _mm_aesenc_si128(block, keys.rk[11]);
  block = _mm_aesenc_si128(block, keys.rk[12]);
  block = _mm_aesenc_si128(block, keys.rk[13]);
  return _mm_aesenclast_si128(block, keys.rk[14]);
}

} // namespace

bool aes_ni_supported() {
  unsigned int eax, ebx, ecx = 0, edx;
  if (!__get_cpuid(1, &eax, &ebx, &ecx, &edx))
    return false;
  return (ecx & (1 << 25)) != 0;
}

// Implements the AES-KDF core loop with AES-NI. This matches the EVP path in
// Key::Transform exactly: seed (32 bytes) is the AES-256 key, in (32 bytes) is
// the data to encrypt; for `rounds` iterations both 16-byte halves of `in`
// are encrypted with AES-256-ECB and the output feeds back as input. out
// receives the result; the caller then SHA-256 hashes it.
void aes_ni_transform_aes_kdf(const uint8_t seed[32], const uint8_t in[32],
                              uint64_t rounds, uint8_t out[32]) {
  const Aes256RoundKeys keys = ExpandKey(seed);

  __m128i a = _mm_loadu_si128(reinterpret_cast<const __m128i *>(in));
  __m128i b = _mm_loadu_si128(reinterpret_cast<const __m128i *>(in + 16));

  for (uint64_t i = 0; i < rounds; ++i) {
    a = EncryptBlock(a, keys);
    b = EncryptBlock(b, keys);
  }

  _mm_storeu_si128(reinterpret_cast<__m128i *>(out), a);
  _mm_storeu_si128(reinterpret_cast<__m128i *>(out + 16), b);
}

} // namespace keepass

#endif // LIBKEEPASS_AES_NI
