name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect

      - name: Install Dependencies
        run: conan install . --output-folder=build --build=missing -s build_type=${{ matrix.build-type }}

      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build-type }} -j $(nproc)

      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build-type }} --output-on-failure

  macos-build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect

      - name: Install Dependencies
        run: conan install . --output-folder=build --build=missing -s build_type=${{ matrix.build-type }}

      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build-type }} -j $(sysctl -n hw.ncpu)

      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build-type }} --output-on-failure

  windows-build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect

      - name: Install Dependencies
        run: conan install . --output-folder=build --build=missing -s build_type=${{ matrix.build-type }}

      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build-type }}

      - name: Test
        working-directory: build
        run: ctest -C ${{ matrix.build-type }} --output-on-failure
